# Generated by Django 4.1 on 2023-02-21 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('problem_category', models.CharField(choices=[('agriculture', 'Agriculture'), ('computer_science', 'Computer Science'), ('social_studies', 'Social Studies'), ('environment', 'Environmental Science'), ('mathematics', 'Mathematics'), ('engineering', 'Engineering'), ('physics', 'physics'), ('chemistry', 'chemistry'), ('other', 'Other')], default='other', max_length=50, verbose_name='Category of the problem')),
                ('problem_brief', models.TextField()),
                ('problem_reward', models.IntegerField(verbose_name='Prize money for providing the solution ')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
