# Generated by Django 4.1 on 2023-02-25 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='text',
            new_name='problem_description',
        ),
    ]
