# Generated by Django 4.1 on 2023-02-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='solution_title',
            field=models.CharField(default='No Title', max_length=50, verbose_name='Solution title'),
            preserve_default=False,
        ),
    ]
