# Generated by Django 4.1 on 2023-02-03 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('ps', 'Problem Solver'), ('pp', 'Problem Provider')], default='pp', max_length=5, verbose_name='Who you are? '),
        ),
    ]
