# Generated by Django 4.1 on 2023-02-26 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemSolver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='Firstname ')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Lastname ')),
                ('id_card_type', models.CharField(choices=[('dl', 'Driving License'), ('adhaar', 'Adhaar Card'), ('passport', 'Passport')], default='adhaar', max_length=50, verbose_name='Personal identity proof type ')),
                ('id_card_number', models.CharField(max_length=10, verbose_name='Personal identity card number ')),
                ('adrress', models.CharField(max_length=200, verbose_name='Address ')),
                ('pin_code', models.IntegerField(verbose_name='Pin Code ')),
                ('ph_no', models.IntegerField(verbose_name='Phone Number ')),
                ('personal_description', models.TextField()),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='username')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=50, verbose_name='Organization name')),
                ('provider_brief', models.CharField(max_length=1000, verbose_name='Brief description')),
                ('govt_liscence_id', models.CharField(max_length=50, verbose_name='Liscence number')),
                ('address', models.CharField(max_length=500, verbose_name='Address ')),
                ('pin_code', models.IntegerField(verbose_name='Pin Code')),
                ('ph_no', models.IntegerField(verbose_name='Phone number')),
                ('personal_description', models.TextField()),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='username')),
            ],
            options={
                'verbose_name': 'ProblemProvider',
                'verbose_name_plural': 'ProblemProviders',
            },
        ),
    ]
