# Generated by Django 4.1 on 2023-02-26 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_problemsolver_problemprovider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemprovider',
            name='ph_no',
            field=models.CharField(max_length=10, verbose_name='Phone Number '),
        ),
        migrations.AlterField(
            model_name='problemprovider',
            name='pin_code',
            field=models.CharField(max_length=6, verbose_name='Pin Code '),
        ),
        migrations.AlterField(
            model_name='problemsolver',
            name='ph_no',
            field=models.CharField(max_length=10, verbose_name='Phone Number '),
        ),
        migrations.AlterField(
            model_name='problemsolver',
            name='pin_code',
            field=models.CharField(max_length=6, verbose_name='Pin Code '),
        ),
    ]
