# Generated by Django 4.1 on 2023-02-26 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_problemprovider_ph_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemprovider',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ProblemProvider', to=settings.AUTH_USER_MODEL, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='problemsolver',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ProblemSolver', to=settings.AUTH_USER_MODEL, verbose_name='username'),
        ),
    ]
