# Generated by Django 4.1 on 2023-02-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_problemprovider_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemprovider',
            name='personal_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
