# Generated by Django 4.1 on 2023-02-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_problemprovider_personal_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemsolver',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Firstname '),
        ),
    ]
