# Generated by Django 4.1 on 2023-02-26 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_problemsolver_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problemsolver',
            old_name='adrress',
            new_name='address',
        ),
    ]
