# Generated by Django 4.1 on 2023-02-26 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_adrress_problemsolver_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemprovider',
            name='username',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProblemProvider', to=settings.AUTH_USER_MODEL, verbose_name='username'),
        ),
    ]
