# Generated by Django 4.1 on 2023-02-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_problemprovider_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemprovider',
            name='address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Address '),
        ),
        migrations.AlterField(
            model_name='problemprovider',
            name='govt_liscence_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Liscence number'),
        ),
        migrations.AlterField(
            model_name='problemprovider',
            name='personal_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='problemprovider',
            name='ph_no',
            field=models.CharField(blank=True, max_length=10, verbose_name='Phone Number '),
        ),
        migrations.AlterField(
            model_name='problemprovider',
            name='pin_code',
            field=models.CharField(blank=True, max_length=6, verbose_name='Pin Code '),
        ),
        migrations.AlterField(
            model_name='problemprovider',
            name='provider_brief',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Brief description'),
        ),
        migrations.AlterField(
            model_name='problemprovider',
            name='provider_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Organization name'),
        ),
    ]
